sparkProp:
  appName: Keywords Matcher
  duration: 2000
meetupProp:
  pathToKeys: /data/conf/meetupkeys
hbaseProp:
  zookeeper: sandbox.hortonworks.com:2181:/hbase-unsecure
hiveProp:
  tableSavePath:  sn_kw
